name: Build ADFinder DMG

on:
  push:
    branches: [master]
    paths:
      - '**'
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug commit message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Contains #build-binary: ${{ contains(github.event.head_commit.message, '#build-binary') }}"

  build:
    needs: debug
    if: contains(github.event.head_commit.message, '#build-binary')
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 1

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Build and package ADFinder
        run: |
          chmod +x distribution/build_and_package.sh distribution/gendmg.sh
          ./distribution/build_and_package.sh --project Amiga/Tools/ADFinder/ADFinder.xcodeproj --scheme ADFinder --configuration Release

      - name: Upload DMG
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ADFinder-DMG
          path: releases/ADFinder-*.dmg
          retention-days: 7
