name: Build and Commit ADFinder DMG

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-commit-dmg:
    if: contains(github.event.head_commit.message, '#build-adfinder')
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Install create-dmg dependency
        run: brew install create-dmg

      - name: Check and select Xcode version
        run: |
          echo "Default Xcode version:"
          xcodebuild -version
          echo "Available Xcode installations:"
          ls -d /Applications/Xcode*.app
          
          for version in 16.2 16.1 16.0 16; do
            if [ -d "/Applications/Xcode_${version}.app" ]; then
              echo "Found Xcode ${version}. Selecting it."
              sudo xcode-select -s "/Applications/Xcode_${version}.app/Contents/Developer"
              break
            fi
          done

          echo "Selected Xcode version:"
          xcodebuild -version

          if [ "$(xcodebuild -version | awk '/Xcode/ {print $2}' | cut -d. -f1)" -lt 16 ]; then
             echo "::error::Failed to select Xcode 16.x. The active version is still less than 16."
             exit 1
          fi

      - name: Build .app and Create .dmg
        id: build_step
        run: |
          set -euo pipefail
          
          cd Amiga/Tools/ADFinder/distribution

          echo "Updating DMG output directory in build script..."
          sed -i '' 's|DMG_DIR="${SCRIPT_DIR}/../releases"|DMG_DIR="${SCRIPT_DIR}/../../releases"|' build_and_package.sh
          
          # Update DMG filename in gendmg.sh to adfinder_build_##.dmg
          sed -i '' 's|DMG_NAME="ADFinder.*"|DMG_NAME="adfinder_build_${BUILD_NUMBER}.dmg"|' gendmg.sh
          
          chmod +x build_and_package.sh
          chmod +x gendmg.sh
          
          echo "▶ Starting build and package script..."
          ./build_and_package.sh --project ../ADFinder.xcodeproj --scheme "ADFinder - Release" --configuration Release
          
          cd ../../../..

          DMG_FILE=$(find Amiga/Tools/releases -name "adfinder_build_*.dmg" -type f -print0 | xargs -0 ls -t | head -n1)
          if [ -z "$DMG_FILE" ]; then
            echo "::error::Could not find the created DMG file from the repo root."
            exit 1
          fi
          echo "Found newest DMG at repo root relative path: $DMG_FILE"
          echo "DMG_FILE=$DMG_FILE" >> $GITHUB_OUTPUT
          
          echo "✅ Build and package script completed successfully."

      - name: Keep only last three DMG builds
        run: |
          cd Amiga/Tools/releases
          # List DMGs, sort by time (oldest first), skip newest 3, delete the rest
          ls -t adfinder_build_*.dmg | tail -n +4 | xargs -I {} git rm {}
          cd ../../..

      - name: Commit and Push DMG
        run: |
          set -euo pipefail
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -- Amiga/Tools/ADFinder/distribution/build_and_package.sh
          git checkout -- Amiga/Tools/ADFinder/distribution/gendmg.sh
          
          DMG_TO_COMMIT="${{ steps.build_step.outputs.DMG_FILE }}"
          echo "Adding '$DMG_TO_COMMIT' to Git."
          git add "$DMG_TO_COMMIT"
          
          if ! git diff --staged --quiet; then
            echo "Committing the new DMG..."
            BUILD_NUMBER=$(echo "$DMG_TO_COMMIT" | sed -n 's/.*_build_//; s/.dmg//p')
            git commit -m "CI: Built ${BUILD_NUMBER} version and generated DMG."
            
            echo "Pushing changes to master..."
            git push origin master
          else
            echo "No new DMG file was created or added. Nothing to commit."
          fi
